// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a134b0d05156a02d4119c1e0c790c6fe4e9f896a/gsap/index.d.ts
declare module 'gsap' {
    export = gsap;
}
